name: Node.js CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    env:
      DB_URL: mongodb+srv://root:xFNqHuDfLCRbbpKy@cluster.nfwhf.mongodb.net/capstonedb?retryWrites=true&w=majority
      MODE: PROD
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run:
       cd app && pwd && npm i && cd frontend && pwd && npm i && npm run build && cd .. && pwd && pm2 stop 2 && pm2 start 2 && pm2 save && sudo service nginx restart
